# Generated by Django 5.2.2 on 2025-06-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='iamge',
            new_name='image',
        ),
    ]
